Repository SoftDevSix/integration-tools, pull requests merged in 2024-10, with the labels that each got.

#2 docs: add description for open PRs
  README.md
Labels: documentation

#3 chore: implement ci notify teams pr opened
  .github/workflows/notify.yml
Labels: chore

#10 chore: implement card for pr in teams
  .github/workflows/notify.yaml
Labels: chore

#11 chore: implement card in merged pr
  .github/workflows/ci.yaml
Labels: chore

#14 chore: implement card in failed pr
  .github/workflows/pull-request.yaml
  Argos/.gradle/8.8/checksums/checksums.lock
  Argos/.gradle/8.8/dependencies-accessors/gc.properties
  Argos/.gradle/8.8/executionHistory/executionHistory.bin
  Argos/.gradle/8.8/executionHistory/executionHistory.lock
  Argos/.gradle/8.8/fileChanges/last-build.bin
  Argos/.gradle/8.8/fileHashes/fileHashes.bin
  Argos/.gradle/8.8/fileHashes/fileHashes.lock
  Argos/.gradle/8.8/fileHashes/resourceHashesCache.bin
  Argos/.gradle/8.8/gc.properties
  Argos/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Argos/.gradle/buildOutputCleanup/cache.properties
  Argos/.gradle/buildOutputCleanup/outputFiles.bin
  Argos/.gradle/file-system.probe
  Argos/.gradle/vcs-1/gc.properties
  Argos/build.gradle.kts
  Argos/build/classes/java/main/org/example/Main.class
  Argos/build/tmp/compileJava/previous-compilation-data.bin
  Argos/gradle/wrapper/gradle-wrapper.jar
  Argos/gradle/wrapper/gradle-wrapper.properties
  Argos/gradlew
  Argos/gradlew.bat
  Argos/settings.gradle.kts
  Argos/src/main/java/org/example/Main.java
Labels: chore, feature

#4 chore: set up Java project using Gradle - Kotlin
  .gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/java/software/development/vi/integration/tools/IntegrationToolsApplication.java
  src/main/resources/application.properties
  src/test/java/software/development/vi/integration/tools/IntegrationToolsApplicationTests.java
Labels: feature

#15 chore: add branch details
  README.md
Labels: documentation, feature
